version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - danger7.0.14
      - run:
          name: Install Dependencies
          command: yarn add danger@7.0.14
      - save_cache:
          name: Save Yarn Package Cache
          key: danger7.0.14
          paths:
            - ~/.cache/yarn
      - run: yarn danger ci